---
  - name: Install libselinux-python bindings required by ansible
    yum: name=libselinux-python

  - name: Disable SELinux
    selinux: state=disabled

  - name: Install latest kernel
    include: kernel.yml
    when: latest_kernel

  - name: Install EPEL
    yum: name=http://mirror.pmf.kg.ac.rs/fedora/epel/6/i386/epel-release-6-8.noarch.rpm

  - name: Install Base Packages
    yum: name={{ item }}
    with_items: packages

  - name: Install tmux config
    copy: src=tmux.conf dest=/etc/tmux.conf mode=0644 owner=root group=root

  - name: Install users
    user: name={{ item.name }} groups={{ item.groups }} append=yes state=present generate_ssh_key=yes ssh_key_bits=1048
    with_items: users
