---

  - name: Install EPEL & docker
    yum: name={{item}}
    with_items:
        - http://mirror.pmf.kg.ac.rs/fedora/epel/6/i386/epel-release-6-8.noarch.rpm
        - docker-io

  - name: Start docker on boot
    service: name=docker enabled=yes

  - name: Docker aliases
    copy: src=docker_aliases.sh dest=/etc/profile.d/docker_aliases.sh
          mode=0644 owner=root group=root

  #- name: Restart machine
    #command: shutdown -r now "Ansible updates triggered"
    #async: 0
    #poll: 0
    #ignore_errors: true

  #- name: Waiting for server to come back
    #local_action: wait_for host={{ inventory_hostname }} state=started
    #sudo: false
