---
- hosts: redserver
  gather_facts: yes
  user: root

  vars:
    latest_kernel: false

  roles:
    - { role: base,           tags: base }
    - { role: docker,         tags: docker }
    - { role: docker_mysql,   tags: mysql }
    - { role: docker_redmine, tags: redmine }
